// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DefaultSuiteTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void insurance1AllValidFieldAge25DrivingEx3Accidents0Insurance3500()
    {
        driver.Navigate().GoToUrl("http://localhost/prog2070a03/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Sowmya");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Bains");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("93 Moffat Ave");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Bramptom");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N3E 0A8");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("905-872-2031");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("bainssowmya@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$3500"));
        }
    }
    [Test]
    public void insurance2AllValidfieldAge25drivingEx3Accidents4NoInsurance()
    {
        driver.Navigate().GoToUrl("http://localhost/prog2070a03/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Sowmya");
        driver.FindElement(By.Id("lastName")).SendKeys("bains");
        driver.FindElement(By.Id("address")).SendKeys("93 moffat ave ");
        driver.FindElement(By.Id("city")).SendKeys("brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L6P 4L1");
        {
            var element = driver.FindElement(By.CssSelector("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).ClickAndHold().Perform();
        }
        {
            var element = driver.FindElement(By.CssSelector("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.CssSelector("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Release().Perform();
        }
        driver.FindElement(By.CssSelector("body")).Click();
        driver.FindElement(By.Id("phone")).Click();
        {
            var element = driver.FindElement(By.Id("phone"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).ClickAndHold().Perform();
        }
        {
            var element = driver.FindElement(By.Id("phone"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.Id("phone"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Release().Perform();
        }
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.CssSelector(".col-md-4:nth-child(1)")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("905-872-2031");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("Bainssowmya@gmail.com");
        driver.FindElement(By.CssSelector(".card-body")).Click();
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("4");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.CssSelector(".card-body")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
        }
    }
    [Test]
    public void insurance3AllValidFieldsAge35DrivingEx10Accidents2Insurance1600()
    {
        driver.Navigate().GoToUrl("http://localhost/prog2070a03/");
        driver.Manage().Window.Size = new System.Drawing.Size(788, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Sowmya");
        driver.FindElement(By.Id("lastName")).SendKeys("Bains");
        driver.FindElement(By.Id("address")).SendKeys("93 moffat ave");
        driver.FindElement(By.Id("city")).SendKeys("brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L6P 4L1");
        driver.FindElement(By.Id("phone")).SendKeys("905-872-2031");
        driver.FindElement(By.Id("email")).SendKeys("bainssowmya@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).SendKeys("10");
        driver.FindElement(By.Id("accidents")).SendKeys("2");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$1600"));
        }
    }
    [Test]
    public void insurance4InvalifPHnoAge27drivingEx3Accidents0NoInsurance()
    {
        driver.Navigate().GoToUrl("http://localhost/prog2070a03/");
        driver.Manage().Window.Size = new System.Drawing.Size(788, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Sowmya");
        driver.FindElement(By.Id("lastName")).SendKeys("bains");
        driver.FindElement(By.Id("address")).SendKeys("93 moffat ave");
        driver.FindElement(By.Id("city")).SendKeys("brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L6P 4L1");
        driver.FindElement(By.Id("phone")).SendKeys("905-87-98");
        driver.FindElement(By.Id("email")).SendKeys("Bainssowmya@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("27");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("phone-error")).Text, Is.EqualTo("Phone Number must follow the patterns 111-111-1111 or (111)111-1111"));
    }
    [Test]
    public void insurance5invalidEmailAge28drivingEx3Accidents0noInsurance()
    {
        driver.Navigate().GoToUrl("http://localhost/prog2070a03/");
        driver.Manage().Window.Size = new System.Drawing.Size(788, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        {
            var element = driver.FindElement(By.Id("firstName"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("firstName")).SendKeys("sowmya");
        driver.FindElement(By.Id("lastName")).SendKeys("bains");
        driver.FindElement(By.Id("address")).SendKeys("93 moffat ave ");
        driver.FindElement(By.Id("city")).SendKeys("brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L6P 4L1");
        driver.FindElement(By.Id("phone")).SendKeys("905-872-2031");
        driver.FindElement(By.Id("email")).SendKeys("Bains.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("28");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("email-error")).Text, Is.EqualTo("Must be a valid email address"));
    }
    [Test]
    public void insurance6invalidpostalcodeAge35drivingEx17Accidents1noInsurance()
    {
        driver.Navigate().GoToUrl("http://localhost/prog2070a03/");
        driver.Manage().Window.Size = new System.Drawing.Size(788, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("sowmya");
        driver.FindElement(By.Id("lastName")).SendKeys("bains");
        driver.FindElement(By.Id("address")).SendKeys("93 moffat ave ");
        driver.FindElement(By.Id("city")).SendKeys("brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("66h hh8");
        driver.FindElement(By.Id("phone")).SendKeys("905-872-2031");
        driver.FindElement(By.Id("email")).SendKeys("Bainssowmya@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).SendKeys("17");
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("postalCode-error")).Text, Is.EqualTo("Postal Code must follow the pattern A1A 1A1"));
    }
    [Test]
    public void insurance7AllvalidFieldsAgeOmitteddrivingEx5Acidents0noInsurance()
    {
        driver.Navigate().GoToUrl("http://localhost/prog2070a03/");
        driver.Manage().Window.Size = new System.Drawing.Size(788, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Sowmya");
        driver.FindElement(By.Id("lastName")).SendKeys("bains");
        driver.FindElement(By.Id("address")).SendKeys("93 moffat ave ");
        driver.FindElement(By.Id("city")).SendKeys("brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L6P 4L1");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("905-872-2031");
        driver.FindElement(By.Id("email")).SendKeys("Bainssowmya@gmail.com");
        driver.FindElement(By.Id("experience")).SendKeys("5");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Age (>=16) is required"));
    }
    [Test]
    public void insurance8AllValidFieldAge37DrivingEx8Accidents0mittedNoInsurance()
    {
        driver.Navigate().GoToUrl("http://localhost/prog2070a03/");
        driver.Manage().Window.Size = new System.Drawing.Size(788, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("sowmya");
        driver.FindElement(By.Id("lastName")).SendKeys("bains");
        driver.FindElement(By.Id("address")).SendKeys("93 moffat ave");
        driver.FindElement(By.Id("city")).SendKeys("Brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L61 4L1");
        driver.FindElement(By.Id("phone")).SendKeys("905-872-2031");
        driver.FindElement(By.Id("email")).SendKeys("BAINSSOWMYA@GMAIL.COM");
        driver.FindElement(By.Id("age")).SendKeys("37");
        driver.FindElement(By.Id("experience")).SendKeys("8");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("accidents-error")).Text, Is.EqualTo("Number of accidents is required"));
    }
    [Test]
    public void insurance9AllValidFieldAge45DrivingExOmittedAccidents0NOInsurance()
    {
        driver.Navigate().GoToUrl("http://localhost/prog2070a03/");
        driver.Manage().Window.Size = new System.Drawing.Size(788, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Sowmya");
        driver.FindElement(By.Id("lastName")).SendKeys("bains");
        driver.FindElement(By.Id("address")).SendKeys("93 Moffat Ave");
        driver.FindElement(By.Id("city")).SendKeys("brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L6P 4L1");
        driver.FindElement(By.Id("phone")).SendKeys("905-872-2031");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("Bainssowmya@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("45");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("experience-error")).Text, Is.EqualTo("Years of experience is required"));
    }
    [Test]
    public void insurance10AllvalidfieldsAge25DrivingEx0Accidents0Insurance5000()
    {
        driver.Navigate().GoToUrl("http://localhost/prog2070a03/");
        driver.Manage().Window.Size = new System.Drawing.Size(788, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("sowmya");
        driver.FindElement(By.Id("lastName")).SendKeys("bains");
        driver.FindElement(By.Id("address")).SendKeys("93 moffat ave");
        driver.FindElement(By.Id("city")).SendKeys("brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L6P 4L1");
        driver.FindElement(By.Id("phone")).SendKeys("905-872-2031");
        driver.FindElement(By.Id("email")).SendKeys("Bainssowmya@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).SendKeys("0");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$5000"));
        }
    }
}
